### PR TITLE
feat: Adds `SKIP_NPM_PUBLISH` and `SKIP_DOCKER_PUBLISH`

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

This enables general usage of this semantic release system without having to publish to NPM (and have a `package.json` file) _or_ have to publish a docker container via this system.

In short, this will enable our other projects (like our Go based ones) to utilize common releasing via GitHub releases and tags without having to pollute our code with NPM boilerplate.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to https://github.com/open-sauced/pizza/pull/42

## Mobile & Desktop Screenshots/Recordings

N/a

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
🚀

**Review by brandonroberts — APPROVED** [review]
🚢 🍕

**Comment by Anush008** [comment]
Yikes. I'll open a separate PR for the changes and #18.

**Pull request merged**
